### ISSUE TITLE
[1.15.2] Crash when opening inventory in creative mode

### ISSUE THREAD

**Issue by TheUntamed** [Tfarcenim/DropOff#10] opened 2020-04-17 22:29 UTC
When opening the inventory in creative mode the game just crashes.
DropOff: 3.0.3 (version 3.0.2 works fine)
Forge: 31.1.45
Crash Report: https://pastebin.com/ruwpUGT7

**Comment by Tfarcenim** [comment] 2020-04-17 22:48
duplicate of #8

**Closed as completed by Tfarcenim** 2020-04-17 22:48 UTC
